services:
  app:
    container_name: pett-app
    image: pett
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_URL=jdbc:mysql://mysql:3306/petclinic
volumes:
  petclinic-vol-mysql:
  petclinic-vol-postgres:
